version: '2.1'
networks: {}
volumes:
  config: {}
  capture: {}
  logs: {}
  web: {}
services:
  basicstation:
    image: xoseperez/basicstation:latest
    container_name: basicstation
    restart: unless-stopped
    privileged: true
    network_mode: host
  datadog-iot:
    build:
      context:  datadog-iot
    privileged: true
    restart: always
    network_mode: host
    pid: host
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.balena-socket: '1'
